PRODUCTS = {"SOLOCAST": "HMIS1X-XX-BK/G",
            "QUADCAST": "HX-MICQC-BK",
            "CLOUD EARBUDS": "HX-HSCEB-RD",

            "CHARGEPLAY DUO": "HX-CPDU-G",
            "CHARGEPLAY DUO XBOX": "HX-CPDUX-G",
            "CHARGEPLAY QUAD": "HX-CPQD-U",
            "CHARGEPLAY CLUTCH": "HX-CPCS-U (SWITCH) HX-CPCM-U (MOBILE)",
            "CHARGEPLAY BASE": "HX-CPBS-G",

            "CLOUD REVOLVER": "HHSR1-AH-GM/G",
            "CLOUD": "HHSC2X-BA-RD/G",
            "CLOUD ORBIT": "HX-HSCO-GM/WW",
            "CLOUD ORBIT S": "HX-HSCOS-GM/WW",
            "CLOUD STINGER": "HX-HSCS-BK/EM",
            "CLOUD STINGER WIRELESS": "HX-HSCSW2-BK/WW (PC)",
            "CLOUD ALPHA S": "HX-HSCAS-BK/WW",
            "CLOUD ALPHA": "HX-HSCA-RD/EM",
            "CLOUDX STINGER": "HX-HSCSX-BK/WW",
            "CLOUDX CHAT": "HX-HSCCHX-BK/WW",
            "CLOUD FLIGHT S": "HX-HSCFS-SG/WW",
            "CLOUD FLIGHT": "HX-HSCF-BK/EM",

            "CONTROLLER BOX": "HXS-HSCB1",
            "CLOUD EARBUDS EAR TIPS": "HXS-HSCEB-RD-ET-L (large) HXS-HSCEB-RD-ET-M (medium) HXS-HSCEB-RD-ET-SM (small)",
            "DUAL 3.5MM PC EXTENSION CABLE": "HXS-HSEC1",
            "CLOUD STINGER WIRELESS ADAPTER": "HXS-HSWA-CSW",
            "CLOUD HEADSET CARRYING CASE": "HXS-HSCC1/EM",
            "CLOUD EARBUDS CARRYING CASE": "HXS-HSCEB-BK-CC",
            "CLOUD EAR CUSHIONS": "HXS-HSEP1 (Black/ Red) HXS-HSEP2 (Black) HXS-HSEP3 (Black/Green)",
            "CLOUD MICROPHONE": "HXS-HSMC1",
            "CLOUD MESH BAG": "HXS-HSBG",
            "CLOUD MIX DETACHABLE CABLE": "HXS-HSDC1",
            "4 POLE TO DUAL 3.5MM PC EXTENSION CABLE": "HXS-HSEC2",
            "CLOUD ALPHA EAR CUSHIONS": "HXS-HSEP4",
            "CLOUD REVOLVER EAR CUSHIONS": "HXS-HSEP5",
            "CLOUD STINGER EAR CUSHIONS": "HXS-HSEP6",
            "3.5MM HEADPHONE CABLE, CLOUD FLIGHT": "HXS-HSHC-CF",
            "CLOUD REVOLVER MICROPHONE": "HXS-HSMC2",
            "CLOUD MICROPHONE (CONSOLE)": "HXS-HSMC3",
            "CLOUD MIX MICROPHONE": "HXS-HSMC4",

            "GG HOODIE": "https://www.hyperxgaming.com/unitedkingdom/en/apparel/gg-hoodie?color=red&size=s",
            "GG TEE": "https://www.hyperxgaming.com/unitedkingdom/en/apparel/gg-tee",
            "GG HAT": "https://www.hyperxgaming.com/unitedkingdom/en/apparel/gg-hat",
            "GG MASK": "https://www.hyperxgaming.com/unitedkingdom/en/apparel/gg-mask",

            "ALLOY CORE RGB": "HX-KB5ME2-UK",
            "ALLOY FPS RGB": "HX-KB1SS2-UK",
            "ALLOY ORIGINS CORE": "HX-KB7AQX-US",
            "ALLOY ORIGINS": "HX-KB6RDX-UK",
            "ALLOY ORIGINS 60": "HKBO1S-RB-US/G",
            "ALLOY ELITE 2": "HKBE2X-1X-UK/G",

            "FURY DDR4 RGB": "HX424C15FB3A/8 https://www.hyperxgaming.com/unitedkingdom/en/memory/fury-ddr4-rgb",
            "FURY DDR4": "HX424C15FB3A/8 https://www.hyperxgaming.com/unitedkingdom/en/memory/fury-ddr4",
            "FURY DDR3": "HX316LC10FB/4 https://www.hyperxgaming.com/unitedkingdom/en/memory/fury-ddr3",
            "PREDATOR DDR4 RGB": "HX429C15PB3A/8 https://www.hyperxgaming.com/unitedkingdom/en/memory/predator-ddr4-rgb",
            "PREDATOR DDR4": "HX424C12PB3/8 https://www.hyperxgaming.com/unitedkingdom/en/memory/predator-ddr4",
            "IMPACT DDR4": "https://www.hyperxgaming.com/unitedkingdom/en/memory/impact-ddr4",
            "IMPACT DDR3": "HX316LS9IB/4 https://www.hyperxgaming.com/unitedkingdom/en/memory/impact-ddr3",

            "PULSEFIRE FPS PRO": "HX-MC003B",
            "PULSEFIRE SURGE": "HX-MC002B",
            "PULSEFIRE CORE": "HX-MC004B",

            "FURY ULTRA RGB": "HX-MPFU-M",
            "FURY S MOUSE PAD": "HX-MPFS-M",
            "FURY S": "HX-MPFS-M",
            "FURY S SPEED": "HX-MPFS-S-M",
            }
